# Generated by Django 4.2.6 on 2023-10-30 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events_tickets.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('date', models.DateField(validators=[events_tickets.custom_validators.validate_date_greater_than_today], verbose_name='date')),
                ('time', models.TimeField(verbose_name='time')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('description', models.TextField(verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_tickets.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_tickets.tickettypes', verbose_name='ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(unique=True, verbose_name='url')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_img', to='events_tickets.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventTicketTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_tickets.event', verbose_name='event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_tickets.tickettypes', verbose_name='ticket')),
            ],
        ),
    ]
