# Generated by Django 4.2.6 on 2023-10-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventTicketTypes',
            new_name='EventTicketType',
        ),
        migrations.RenameModel(
            old_name='TicketTypes',
            new_name='TicketType',
        ),
    ]
