# Generated by Django 4.2.6 on 2023-11-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_tickets', '0002_rename_eventtickettypes_eventtickettype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
